site_name: JamJar
theme:
  name: material
  features:
    - navigation.indexes
markdown_extensions:
  - mdx_truly_sane_lists
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
plugins:
  - search
