name: build
on:
  push:
  pull_request:
  release:
    types: [created]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container: registry.access.redhat.com/ubi8/ubi-minimal:8.5-218
    steps:
    - name: Check out code into the CI directory
      uses: actions/checkout@v1
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: 2.0.34
    - name: Install build dependencies
      run: |
        # Install required tools
        dnf update
        dnf install clang clang-tools-extra cmake libsdl2-dev git -y

        # Install SDL2
        git clone https://github.com/libsdl-org/SDL
        cd SDL
        mkdir build
        cd build
        ../configure
        make
        make install

        # Print versions for debugging
        cmake --version
        em++ --version
        clang --version
        clang-format --version
        clang-tidy --version
    - name: Lint, beautify, and build
      env:
        CC: emcc
        CXX: em++
      run: |

        # Set up build
        emcmake cmake -D CMAKE_EXPORT_COMPILE_COMMANDS=ON . -B build
        cd build

        # Lint and beautify, fail if there is a difference after beautification
        # make lint - disabled until linting is fixed
        make beautify
        git diff --exit-code

        # Build the project
        make

        # Clean up build
        cd ..
        rm -rf build/
    - name: Test
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
      run: |

        # Set up build
        cmake -D CMAKE_EXPORT_COMPILE_COMMANDS=ON . -B build
        cd build

        # Build unit tests
        make JamJarTests

        # Run unit tests
        ctest
