name: build
on:
  push:
  pull_request:
  release:
    types: [created]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container: jamjarlabs/jamjar-build-image:v0.1.0
    steps:
    - name: Check out code into the CI directory
      uses: actions/checkout@v1
    - name: Lint, beautify, and build
      env:
        CC: emcc
        CXX: em++
      run: |

        # Set up build
        emcmake cmake -D CMAKE_EXPORT_COMPILE_COMMANDS=ON . -B build
        cd build

        # Lint and beautify, fail if there is a difference after beautification
        make lint
        make beautify
        git diff --exit-code

        # Build the project
        make

        # Clean up build
        cd ..
        rm -rf build/
    - name: Test
      env:
        CC: clang
        CXX: clang
      run: |

        # Set up build
        cmake -D CMAKE_EXPORT_COMPILE_COMMANDS=ON . -B build
        cd build

        # Build unit tests
        make JamJarTests

        # Run unit tests
        ctest
