name: main
on:
  push:
  pull_request:
  release:
    types: [created]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code into the CI directory
      uses: actions/checkout@v1
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v9
      with:
        emscripten-version: '2.0.20'
    - name: Lint, test and build
      env:
        CC: emcc
        CXX: em++
      run: |

        # Install required tools
        sudo apt-get install clang-11 clang-tidy-11 clang-format-11 cmake -y

        # Link tools to expected locations
        sudo ln -sf /usr/bin/clang-11 /usr/bin/clang
        sudo ln -sf /usr/bin/clang++-11 /usr/bin/clang++
        sudo ln -sf /usr/bin/clang-tidy-11 /usr/bin/clang-tidy
        sudo ln -sf /usr/bin/clang-format-11 /usr/bin/clang-format

        # Print versions for debugging
        cmake --version
        em++ --version
        clang --version
        clang-format --version
        clang-tidy --version

        # Install shared dependencies
        sudo apt-get install libsdl2-dev

        # Set up build
        cmake -D CMAKE_EXPORT_COMPILE_COMMANDS=ON . -B build
        cd build

        # Lint and beautify, fail if there is a difference after beautification
        make lint
        make beautify
        git diff --exit-code

        # Build the project
        make

        # Run unit tests
        ctest
